name: medicle_sales_rbsh
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#-------------------- PACKAGE ------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Package
  http: ^0.13.1
  intl: ^0.18.1
  logger: ^2.1.0
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  date_picker_plus: ^4.1.0
  quickalert: ^1.1.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  in_app_update: ^4.2.3


  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Related
  fl_chart: ^0.67.0
  pdf: ^3.10.8
  flutter_pdfview: ^1.2.7
  dio: ^5.3.3
  cached_network_image: ^3.3.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  stylish_bottom_bar: ^1.1.0


#-------------------- /PACKAGE END ------------#



#-------------------- DEV DEPENDENCIES ------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png" # Update with your icon path
  adaptive_icon_background: "#ffffff" # Background color for Android adaptive icons
  #adaptive_icon_foreground: "assets/app_icon/adaptive_icon.png" # Optional foreground

flutter:
  uses-material-design: true
  #---------- Local Assets ---------------------#

  assets:
    - assets/logos/
    - assets/app_icon/
    - assets/images/dummy.jpeg
    - assets/images/pdf.png

  #------------- Local fonts-------------------#


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800