org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true

# Keystore configuration
storePassword=GlucksCare@12345
keyPassword=GlucksCare@12345
keyAlias=upload
storeFile=upload-keystore.jks

android.compileSdk=34
flutter.minSdkVersion=21
flutter.targetSdkVersion=34
flutter.compileSdkVersion=





#android.enableDexingArtifactTransform.desugaring=true


