org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Keystore configuration
storePassword=GlucksCare@12345
keyPassword=GlucksCare@12345
keyAlias=upload
storeFile=upload-keystore.jks

android.compileSdk=35

#android.enableDexingArtifactTransform.desugaring=true
