// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_olg0tyjosUkZrjY-5bQtV-bbty2DhE',
    appId: '1:83559767175:web:a2eb89e60afe730a5eac22',
    messagingSenderId: '83559767175',
    projectId: 'gluckscaresalespro-ca891',
    authDomain: 'gluckscaresalespro-ca891.firebaseapp.com',
    storageBucket: 'gluckscaresalespro-ca891.firebasestorage.app',
    measurementId: 'G-DJ1SQ05FQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1iTfmgVV1QlFmVbYoJ3vdOEncPBXN_t8',
    appId: '1:83559767175:android:557c26e056d150e75eac22',
    messagingSenderId: '83559767175',
    projectId: 'gluckscaresalespro-ca891',
    storageBucket: 'gluckscaresalespro-ca891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4D0xXX3jKf9IdRhdM2Iu3P4VrGfs4Yfw',
    appId: '1:83559767175:ios:fd399342f802bbec5eac22',
    messagingSenderId: '83559767175',
    projectId: 'gluckscaresalespro-ca891',
    storageBucket: 'gluckscaresalespro-ca891.firebasestorage.app',
    iosBundleId: 'com.rbsh.medicleSalesRbsh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4D0xXX3jKf9IdRhdM2Iu3P4VrGfs4Yfw',
    appId: '1:83559767175:ios:fd399342f802bbec5eac22',
    messagingSenderId: '83559767175',
    projectId: 'gluckscaresalespro-ca891',
    storageBucket: 'gluckscaresalespro-ca891.firebasestorage.app',
    iosBundleId: 'com.rbsh.medicleSalesRbsh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4_olg0tyjosUkZrjY-5bQtV-bbty2DhE',
    appId: '1:83559767175:web:f2bfe5b99d6fd4d15eac22',
    messagingSenderId: '83559767175',
    projectId: 'gluckscaresalespro-ca891',
    authDomain: 'gluckscaresalespro-ca891.firebaseapp.com',
    storageBucket: 'gluckscaresalespro-ca891.firebasestorage.app',
    measurementId: 'G-849VDR08J9',
  );
}
